add: LoacConfig() function

diff --git a/preview b/preview
--- a/preview
+++ b/preview
@@ -17,6 +17,24 @@ Log() {
    fi
 }
 
+LoadConfig() {
+   default_conf="$VIFM/scripts/$SCRIPT_NAME/preview.conf"
+   user_conf="$VIFM/preview.conf"
+   # echo "default_conf=$default_conf" >>~/.cache/vifm/preview/test
+   # echo "user_conf   =$user_conf" >>~/.cache/vifm/preview/test
+   if [ -f "$user_conf" ]; then
+      source "$user_conf"
+      # echo "user_conf is loaded" >>~/.cache/vifm/preview/test
+      return 0
+   elif [ -f "$default_conf" ]; then
+      source "$default_conf"
+      # echo "default_conf is loaded" >>~/.cache/vifm/preview/test
+      return 0
+   fi
+   echo "[ERROR]: Cannot find 'preview.conf'."
+   return 1
+}
+
 GetHash() {
    local path="$1"
    local hash=$(realpath "$path" | sha256sum | cut -d' ' -f1)
@@ -275,20 +293,6 @@ Main() {
 }
 
 # --------------------------------------------------------------------------------
-# Source config
-# --------------------------------------------------------------------------------
-default_config="$VIFM/scripts/$SCRIPT_NAME/preview.conf"
-user_config="$VIFM/preview.conf"
-if [ -f "$user_config" ]; then
-   source "$user_config"
-elif [ -f "$default_config" ]; then
-   source "$default_config"
-else
-   echo "[ERROR]: Cannot find 'preview.conf'."
-   exit
-fi
-
-# --------------------------------------------------------------------------------
 # Global variables
 # --------------------------------------------------------------------------------
 
@@ -316,15 +320,10 @@ else
    IS_NVIM=1
 fi
 
-# echo "dadaa"
-# echo $ENV
-# echo $IS_NVIM
-# if IsContained "$ENV" "nvim"; then
-#    echo "nvim is contained"
-#    # nvimが含まれている場合の処理
-# else
-#    echo "nvim is not contained"
-# fi
+# Load config
+if ! LoadConfig; then
+   exit
+fi
 
 # Execute Main()
 Main
