Release v2.0.4

diff --git a/preview b/preview
--- a/preview
+++ b/preview
@@ -8,13 +8,30 @@ SCRIPT_NAME='preview.vifm'
 
 # Loging
 Log() {
-   local category="$1"
-   local label="$2"
+   local subcmd=$1
+   local category="$2"
    local value="$3"
-   local length=20
-   if [[ $LOG_ENABLED == true ]]; then
-      printf "[ %-${length}s ] %-${length}s: %s\n" "$category" "$label" "$value" >>"$LOG_PATH"
+   if [[ $LOG_ENABLED -eq 0 ]]; then
+      printf "[ %-5s ] %-22s: %s\n" "$subcmd" "$category" "$value" >>"$LOG_PATH"
    fi
+}
+
+LoadConfig() {
+   default_conf="$VIFM/scripts/$SCRIPT_NAME/preview.conf"
+   user_conf="$VIFM/preview.conf"
+   # echo "default_conf=$default_conf" >>~/.cache/vifm/preview/test
+   # echo "user_conf   =$user_conf" >>~/.cache/vifm/preview/test
+   if [ -f "$user_conf" ]; then
+      source "$user_conf"
+      # echo "user_conf is loaded" >>~/.cache/vifm/preview/test
+      return 0
+   elif [ -f "$default_conf" ]; then
+      source "$default_conf"
+      # echo "default_conf is loaded" >>~/.cache/vifm/preview/test
+      return 0
+   fi
+   echo "[ERROR]: Cannot find 'preview.conf'."
+   return 1
 }
 
 GetHash() {
@@ -105,7 +122,7 @@ GeneratePreview() {
    local path="$2"
    local force=$3
 
-   Log "preview.start" "$action" "file='$path'"
+   Log "$action" "generate.start" "file='$path'"
 
    # Get preview filename (hash)
    local hash=$(GetHash "$path")
@@ -117,7 +134,7 @@ GeneratePreview() {
          # magick "$file" -quality $IMAGE_QUALITY -resize $IMAGE_SIZE $COLOR_SPACE "$preview_path" &>/dev/null # '&' at last works async ?
          local colorspace=$(magick identify -format "%[colorspace]" "$path" 2>/dev/null)
 
-         if [[ $colorspace == "CMYK" && $IMAGE_COLORSPACE_CMYK_TO_SRGB == true ]]; then
+         if [[ $colorspace == "CMYK" && $IMAGE_COLORSPACE_CMYK_TO_SRGB -eq 0 ]]; then
             magick "$path" -quality $IMAGE_QUALITY -resize $IMAGE_SIZE -colorspace sRGB "$preview_path" &>/dev/null
          else
             magick "$path" -quality $IMAGE_QUALITY -resize $IMAGE_SIZE "$preview_path" &>/dev/null
@@ -126,12 +143,12 @@ GeneratePreview() {
          # ffmpeg -y -i "$file" -vf "select='eq(n,$VIDEO_FRAME)',scale=$VIDEO_SIZE" -frames:v 1 "$preview_path" &>/dev/null # '&' at last works async ?
          ffmpegthumbnailer -s $VIDEO_SIZE -q $VIDEO_QUALITY -t $VIDEO_SEEK_TIME -i "$path" -o "$preview_path" &>/dev/null # '&' at last works async ?
       else
-         Log "preview.error" "'$action' is not a valid action."
+         Log "$action" "generate.error" "'$action' is not a valid action."
       fi
    fi
 
-   Log "preview.path" "$action" "path='$path'"
-   Log "preview.end" "$action" "processed '$path'"
+   Log "$action" "generate.path" "path='$path'"
+   Log "$action" "generate.end" "processed '$path'"
    echo $preview_path
 }
 
@@ -144,14 +161,14 @@ GeneratePreviewAll() {
 
    local cnt=0
 
-   Log "preview_all.start" "$action" "dir='$dir'"
+   Log "$action" "generate_all.start" "dir='$dir'"
 
    local status=$(GetStatus "$dir" "$action")
    if [[ $status == "done" && "$force" != "force" ]]; then
-      Log "preview_all.status" "$action" "Skip generating all in '$dir' (already generated)"
+      Log "$action" "generate_all.status" "Skip generating all in '$dir' (already generated)"
       return 1
    elif [[ $status == "locked" ]]; then
-      Log "preview_all.status" "$action" "Skip generating all in '$dir' (generating now)"
+      Log "$action" "generate_all.status" "Skip generating all in '$dir' (generating now)"
       return 1
    fi
 
@@ -161,34 +178,29 @@ GeneratePreviewAll() {
    IFS=',' read -r -a pat_array <<<"$patterns"
    local jobs=()
    for pat in "${pat_array[@]}"; do
-      Log "preview_all.pattern" "$action" "pat='$pat'"
+      Log "$action" "generate_all.pattern" "pat='$pat'"
       # For each pattern, find matching files
       for file in "$dir"/$pat; do
          # Only proceed if $file is a regular file
          if [[ -f "$file" ]]; then
-            Log "preview_all.file" "$action" "file='$file'"
-            # local preview_path=$(GeneratePreview $action "$file" &)
+            Log "$action" "generate_all.file" "file='$file'"
             GeneratePreview $action "$file" $force &
-            # jobs+=($!) # TODO: REMOVE
             ((cnt++))
          fi
       done
    done
 
-   # wait "${jobs[@]}" # ERROR: "PID * is not a valid child process" # TODO: REMOVE
    wait
 
    SetStatus "$dir" "$action" "done"
-   Log "preview_all.end" "$action" "processed $cnt files in '$dir'"
+   Log "$action" "generate_all.end" "processed $cnt files in '$dir'"
 }
 
 # Replace % placeholders to actual values
 GetCmd() {
    local cmd="$1"
    local preview_path="$2"
-   Log "get_cmd.start" "" ""
-   Log "get_cmd.template" "" "cmd='$1'"
-   Log "get_cmd.path" "" "preview_path='$preview_path'"
+   Log "$action" "get_cmd.path" "preview_path='$preview_path'"
 
    # Replace
    cmd="${cmd//%pw/$PW}"
@@ -200,22 +212,22 @@ GetCmd() {
       cmd="${cmd//%file/$preview_path}"
    fi
 
-   Log "get_cmd.cmd" "" "$cmd"
+   Log "$action" "get_cmd.cmd" "$cmd"
    echo "$cmd"
 }
 
 # Clear
 Clear() {
-   Log "clear.start" "" ""
+   Log "$SUBCMD" "clear.start" ""
    local cmd_clear=$(GetCmd "$CLEAR_CMD_TEMPLATE" "")
    sh -c "$cmd_clear"
-   Log "clear.end" "" ""
+   Log "$SUBCMD" "clear.end" ""
 }
 
 # Show preview
 Show() {
    local path="$1"
-   Log "show.start" "" ""
+   Log "$SUBCMD" "show.start" "$path"
    # Adjust x,y on nvim
    if [[ $IS_NVIM ]]; then
       PX=$((PX + VIFM_PREVIEW_WIN_X + VIFM_PREVIEW_WIN_BORDER_WIDTH))
@@ -223,7 +235,7 @@ Show() {
    fi
    local cmd_show=$(GetCmd "$SHOW_CMD_TEMPLATE" "$path")
    sh -c "$cmd_show"
-   Log "show.end" "" "$path"
+   Log "$SUBCMD" "show.end" "$path"
 }
 
 # --------------------------------------------------------------------------------
@@ -232,14 +244,17 @@ Show() {
 Main() {
    # Logging
    Log "" "" ""
-   Log "main.start" "$SUBCMD" "----------------------------------------------------------"
-   Log "ctx" "subcmd" "$SUBCMD"
-   Log "ctx" "path" "$TARGET_PATH"
-   Log "ctx" "size" "$PW x $PH"
-   Log "ctx" "pos" "$PX x $PY"
-   Log "ctx" "cur_dir" "$cur_dir"
-   Log "ctx" "cmd_show_template" "$SHOW_CMD_TEMPLATE"
-   Log "ctx" "cmd_clear_template" "$CLEAR_CMD_TEMPLATE"
+   Log "$SUBCMD" "main.start" "----------------------------------------------------------"
+   Log "$SUBCMD" "ctx" "subcmd=$SUBCMD"
+   Log "$SUBCMD" "ctx" "target_path=$TARGET_PATH"
+   Log "$SUBCMD" "ctx" "size=$PW x $PH"
+   Log "$SUBCMD" "ctx" "pos=$PX x $PY"
+   Log "$SUBCMD" "ctx" "CMD_SHOW_TEMPLATE='$SHOW_CMD_TEMPLATE'"
+   Log "$SUBCMD" "ctx" "CMD_CLEAR_TEMPLATE='$CLEAR_CMD_TEMPLATE'"
+   Log "$SUBCMD" "ctx" "CMD_CLEAR_TEMPLATE='$CLEAR_CMD_TEMPLATE'"
+   Log "$SUBCMD" "ctx" "VIFM_PREVIEW_WIN_X=$VIFM_PREVIEW_WIN_X"
+   Log "$SUBCMD" "ctx" "VIFM_PREVIEW_WIN_Y=$VIFM_PREVIEW_WIN_Y"
+   Log "$SUBCMD" "ctx" "VIFM_PREVIEW_WIN_BORDER_WIDTH=$VIFM_PREVIEW_WIN_BORDER_WIDTH"
 
    # Create cache directory
    mkdir -p "$CACHE_DIR"
@@ -273,19 +288,6 @@ Main() {
 }
 
 # --------------------------------------------------------------------------------
-# Source config
-# --------------------------------------------------------------------------------
-config="$VIFM/scripts/$SCRIPT_NAME/config"
-if [ -f "$config" ]; then
-   source "$config"
-elif [ -f "$config.default" ]; then
-   source "$config.default"
-else
-   echo "[ERROR]: 'config' or 'config.default' not exists."
-   exit
-fi
-
-# --------------------------------------------------------------------------------
 # Global variables
 # --------------------------------------------------------------------------------
 
@@ -307,7 +309,16 @@ PARENT=$(GetParentDir "$TARGET_PATH")
 ENV=$(GetEnvironment)
 
 # On nvim or not
-IS_NVIM=$(IsContained "$ENV" "nvim")
+if IsContained "$ENV" "nvim"; then
+   IS_NVIM=0
+else
+   IS_NVIM=1
+fi
+
+# Load config
+if ! LoadConfig; then
+   exit
+fi
 
 # Execute Main()
 Main
